name: Bug Report
description: Report a problem or unexpected behavior in the project
title: "[BUG] "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Please make sure to check the following before submitting a bug report

        - [ ] I have read the [contribution guide](https://github.com/kestrelchat/.github/blob/master/.github/CONTRIBUTING.md)
        - [ ] I am reporting a reproducible problem in the project

  - type: input
    id: bug_summary
    attributes:
      label: Summary
      description: Provide a short summary of the bug
      placeholder: The login page crashes on invalid credentials

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the issue
      placeholder: |
        1. Open the login page
        2. Enter invalid credentials
        3. Click login
        4. See the error

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: An error message should display without crashing

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What actually happens
      placeholder: The page crashes with a 500 error

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any extra info, logs, or screenshots
      placeholder: Add screenshots, logs, or relevant info here
